application:
  meta:
    name: H4G_ULI_Management
    description: H4G ULI Management
    author: Omer Narmanlioglu
  schema:
    - name: LOG_LIMIT
      displayName: LOG_LIMIT
      description: LOG_LIMIT.
      defaultValue: 5000
      type: number
      group: General Settings
    - name: NaaS_IP
      displayName: NaaS URL
      description: NaaS URL
      defaultValue: "https://naas.chime-prod.gcp.de.pri.o2.com/naas"
      type: string
      group: General Settings
    - name: XPaaS_IP
      displayName: XPaaS URL
      description: XPaaS URL
      defaultValue: "https://xpaas.chime-prod.gcp.de.pri.o2.com/xpaas"
      type: string
      group: General Settings
    - name: PGW_IP
      displayName: PGW URL
      description: PGW URL
      defaultValue: "https://pgw.chime-prod.gcp.de.pri.o2.com/pgw"
      type: string
      group: General Settings
    - name: Auth_IP
      displayName: Auth URL
      description: Auth URL
      defaultValue: "https://am.chime-prod.gcp.de.pri.o2.com/gateway/chime/oauth/token"
      type: string
      group: General Settings
    - name: CLIENT_ID
      displayName: Client ID
      description: Client ID
      defaultValue: ""
      type: string
      group: General Settings
    - name: CLIENT_SECRET
      displayName: Client SECRET
      description: Client SECRET
      defaultValue: ""
      type: string
      group: General Settings
    - name: NAAS_CLUSTER
      displayName: NaaS Cluster
      description: Name of NaaS cluster for this application.
      defaultValue: "S_P1_M1"
      type: string
      group: General Settings
    - name: PROVISION_MODE
      displayName: Provision Mode (OPEN_LOOP, OFFLINE_SIM, ONLINE_SIM, OPERATIONAL)
      description: Provision Mode (OPEN_LOOP, OFFLINE_SIM, ONLINE_SIM, OPERATIONAL)
      defaultValue: "OFFLINE_SIM"
      type: string
      group: General Settings
    - name: ACTION_LIMIT
      displayName: Maximum Allowed Action Count per Task
      description: Maximum Allowed Action Count per Task
      defaultValue: -1
      type: number
      group: General Settings
    - name: BATCH_SIZE
      displayName: Batch Size For XPaaS Request
      description: Batch Size For XPaaS Request
      defaultValue: 500
      type: number
      group: General Settings
    - name: BACKLOG_DURATION
      displayName: Backlog Duration For XPaaS Request
      description: Backlog Duration XPaaS Request
      defaultValue: "72h"
      type: string
      group: General Settings
    - name: MIN_REQ_ATTEMPT_THRESHOLD_FOR_ULI_2
      displayName: Minimum Required SgNB Addition Attempt For ULI of 2
      description: Minimum Required SgNB Addition Attempt For ULI of 2
      defaultValue: 100
      type: number
      group: General Settings
    - name: MIN_REQ_ATTEMPT_THRESHOLD_FOR_ULI_NOT_2
      displayName: Minimum Required SgNB Addition Attempt For ULI of Not 2
      description: Minimum Required SgNB Addition Attempt For ULI of Not 2
      defaultValue: 50
      type: number
      group: General Settings
    - name: MIN_REQ_SR_THRESHOLD
      displayName: Minimum Required SgNB Addition Success Ratio
      description: Minimum Required SgNB Addition Success Ratio
      defaultValue: 90
      type: number
      group: General Settings