application:
  meta:
    name: chime-app-1
    version: 1.0
    description: This is a prototype chime application
    author:
  schema:
    - name: NAAS_CLUSTER
      displayName: NaaS Cluster
      description: Name of NaaS cluster for this application
      defaultValue:
      type: string
      group: General Settings