# Configure parameter values for development time. These will be overriden at runtime with the user provided data
NAAS_CLUSTER: "S_P1_M1_ULI"
PROVISION_MODE: "OFFLINE_SIM" # "OFFLINE_SIM, OPERATIONAL"
BACKLOG_DURATION: "72h"
BATCH_SIZE: 500
MIN_REQ_SR_THRESHOLD: 90
MIN_REQ_ATTEMPT_THRESHOLD: 100
ACTION_LIMIT: -1